trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infra-aib/**
    exclude:
      - infra-aib/.terraform.lock.hcl

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: terraform-state-config-aib
  - name: terraformVersion
    value: '1.14.3'
  - name: workingDirectory
    value: '$(System.DefaultWorkingDirectory)/infra-aib'
  - name: serviceConnection
    value: 'sp-ado-cuadmproj-containers'
  - name: ado-environment
    value: 'labs'

stages:
  - stage: CheckProviders
    displayName: 'Check Azure Provider Registration'
    jobs:
      - job: VerifyProviders
        displayName: 'Verify Required Providers'
        steps:
          - task: AzureCLI@2
            displayName: 'Check Azure Provider Registration Status'
            inputs:
              azureSubscription: '$(serviceConnection)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Checking Azure provider registration status..."
                echo ""
                
                # Define required providers
                PROVIDERS=(
                  "Microsoft.VirtualMachineImages"
                  "Microsoft.KeyVault"
                  "Microsoft.Compute"
                  "Microsoft.Storage"
                  "Microsoft.Network"
                  "Microsoft.ContainerInstance"
                )
                
                ALL_REGISTERED=true
                
                # Check each provider
                for PROVIDER in "${PROVIDERS[@]}"; do
                  echo "Checking provider: $PROVIDER"
                  STATE=$(az provider show -n "$PROVIDER" --query "registrationState" -o tsv)
                  echo "  Registration State: $STATE"
                  
                  if [ "$STATE" != "Registered" ]; then
                    echo "  ⚠️  WARNING: Provider $PROVIDER is not registered (State: $STATE)"
                    ALL_REGISTERED=false
                  else
                    echo "  ✓ Provider is registered"
                  fi
                  echo ""
                done
                
                if [ "$ALL_REGISTERED" = false ]; then
                  echo "##vso[task.logissue type=warning]Some Azure providers are not registered. Consider registering them with 'az provider register --namespace <provider-name>'"
                  echo ""
                  echo "To register all required providers, run:"
                  echo "az provider register --namespace Microsoft.VirtualMachineImages"
                  echo "az provider register --namespace Microsoft.KeyVault"
                  echo "az provider register --namespace Microsoft.Compute"
                  echo "az provider register --namespace Microsoft.Storage"
                  echo "az provider register --namespace Microsoft.Network"
                  echo "az provider register --namespace Microsoft.ContainerInstance"
                  exit 1
                else
                  echo "✓ All required Azure providers are registered"
                fi

  - stage: Validate
    displayName: 'Validate Terraform'
    dependsOn: CheckProviders
    jobs:
      - job: ValidateTerraform
        displayName: 'Terraform Validate'
        steps:
          - template: tasks/install-terraform.yml
            parameters:
              terraformVersion: $(terraformVersion)

          - template: tasks/setup-azure-auth.yml
            parameters:
              serviceConnection: $(serviceConnection)

          - template: tasks/terraform-init.yml
            parameters:
              workingDirectory: $(workingDirectory)
              serviceConnection: $(serviceConnection)
              tfStateResourceGroup: $(tfStateResourceGroup)
              tfStateStorageAccount: $(tfStateStorageAccount)
              tfStateContainer: $(tfStateContainer)
              tfStateKey: $(tfStateKey)

          - template: tasks/terraform-validate.yml
            parameters:
              workingDirectory: $(workingDirectory)

          - template: tasks/terraform-format-check.yml
            parameters:
              workingDirectory: $(workingDirectory)
              serviceConnection: $(serviceConnection)

  - stage: Plan
    displayName: 'Plan Infrastructure'
    dependsOn: Validate
    jobs:
      - job: TerraformPlan
        displayName: 'Terraform Plan'
        steps:
          - template: tasks/install-terraform.yml
            parameters:
              terraformVersion: $(terraformVersion)

          - template: tasks/setup-azure-auth.yml
            parameters:
              serviceConnection: $(serviceConnection)

          - template: tasks/terraform-init.yml
            parameters:
              workingDirectory: $(workingDirectory)
              serviceConnection: $(serviceConnection)
              tfStateResourceGroup: $(tfStateResourceGroup)
              tfStateStorageAccount: $(tfStateStorageAccount)
              tfStateContainer: $(tfStateContainer)
              tfStateKey: $(tfStateKey)

          - template: tasks/terraform-plan.yml
            parameters:
              workingDirectory: $(workingDirectory)
              serviceConnection: $(serviceConnection)
              commandOptions: '-out=tfplan'

          - task: PublishPipelineArtifact@1
            displayName: 'Publish Plan Artifact'
            inputs:
              targetPath: '$(workingDirectory)/tfplan'
              artifact: 'tfplan'
              publishLocation: 'pipeline'

  - stage: Apply
    displayName: 'Deploy Infrastructure'
    dependsOn: Plan
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - deployment: DeployInfrastructure
        displayName: 'Apply Terraform'
        environment: $(ado-environment)
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - template: tasks/install-terraform.yml
                  parameters:
                    terraformVersion: $(terraformVersion)

                - template: tasks/setup-azure-auth.yml
                  parameters:
                    serviceConnection: $(serviceConnection)

                - task: AzureCLI@2
                  displayName: 'Verify Azure CLI'
                  inputs:
                    azureSubscription: '$(serviceConnection)'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      echo "Azure CLI Version:"
                      az --version

                - template: tasks/terraform-init.yml
                  parameters:
                    workingDirectory: $(workingDirectory)
                    serviceConnection: $(serviceConnection)
                    tfStateResourceGroup: $(tfStateResourceGroup)
                    tfStateStorageAccount: $(tfStateStorageAccount)
                    tfStateContainer: $(tfStateContainer)
                    tfStateKey: $(tfStateKey)

                - template: tasks/terraform-apply.yml
                  parameters:
                    workingDirectory: $(workingDirectory)
                    serviceConnection: $(serviceConnection)
                    commandOptions: '-auto-approve'

                - task: AzureCLI@2
                  displayName: 'Create Image Template'
                  inputs:
                    azureSubscription: '$(serviceConnection)'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    workingDirectory: $(workingDirectory)
                    inlineScript: |
                      echo "Creating Azure Image Builder template..."
                      
                      # Get Terraform outputs
                      RESOURCE_GROUP=$(terraform output -raw resource_group_name)
                      TEMPLATE_NAME=$(terraform output -raw image_template_resource_name)
                      TEMPLATE_FILE=$(terraform output -raw image_template_json_filename)
                      
                      # Create the Image Template resource
                      az resource create \
                        --resource-group "$RESOURCE_GROUP" \
                        --properties @"$TEMPLATE_FILE" \
                        --is-full-object \
                        --resource-type Microsoft.VirtualMachineImages/imageTemplates \
                        --name "$TEMPLATE_NAME"
                      
                      echo "Image template '$TEMPLATE_NAME' created successfully"

                - task: AzureCLI@2
                  displayName: 'Build Custom Image'
                  inputs:
                    azureSubscription: '$(serviceConnection)'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    workingDirectory: $(workingDirectory)
                    inlineScript: |
                      echo "Starting image build process..."
                      
                      # Get Terraform outputs
                      RESOURCE_GROUP=$(terraform output -raw resource_group_name)
                      TEMPLATE_NAME=$(terraform output -raw image_template_resource_name)
                      
                      # Invoke the image build action
                      az resource invoke-action \
                        --resource-group "$RESOURCE_GROUP" \
                        --resource-type Microsoft.VirtualMachineImages/imageTemplates \
                        --name "$TEMPLATE_NAME" \
                        --action Run
                      
                      echo "Image build triggered successfully for template '$TEMPLATE_NAME'"
                      echo "Note: The build process runs asynchronously and may take several minutes to complete."

                - task: AzureCLI@2
                  displayName: 'Check Image Build Status'
                  inputs:
                    azureSubscription: '$(serviceConnection)'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    workingDirectory: $(workingDirectory)
                    inlineScript: |
                      echo "Checking image template status..."
                      
                      # Get Terraform outputs
                      RESOURCE_GROUP=$(terraform output -raw resource_group_name)
                      TEMPLATE_NAME=$(terraform output -raw image_template_resource_name)
                      
                      # Check the template status
                      STATUS=$(az resource show \
                        --resource-group "$RESOURCE_GROUP" \
                        --resource-type Microsoft.VirtualMachineImages/imageTemplates \
                        --name "$TEMPLATE_NAME" \
                        --query "properties.lastRunStatus.runState" -o tsv)
                      
                      echo "Current build status: $STATUS"
                      
                      # Optional: Wait for completion (can be commented out if you want async behavior)
                      # while [ "$STATUS" != "Succeeded" ] && [ "$STATUS" != "Failed" ]; do
                      #   echo "Build still in progress... waiting 30 seconds"
                      #   sleep 30
                      #   STATUS=$(az resource show \
                      #     --resource-group "$RESOURCE_GROUP" \
                      #     --resource-type Microsoft.VirtualMachineImages/imageTemplates \
                      #     --name "$TEMPLATE_NAME" \
                      #     --query "properties.lastRunStatus.runState" -o tsv)
                      #   echo "Status: $STATUS"
                      # done
                      
                      if [ "$STATUS" == "Failed" ]; then
                        echo "##vso[task.logissue type=error]Image build failed"
                        exit 1
                      fi

                - task: AzureCLI@2
                  displayName: 'Cleanup Image Template Resources'
                  inputs:
                    azureSubscription: '$(serviceConnection)'
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    workingDirectory: $(workingDirectory)
                    inlineScript: |
                      echo "Cleaning up image template staging resources..."
                      
                      # Get Terraform outputs
                      RESOURCE_GROUP=$(terraform output -raw resource_group_name)
                      TEMPLATE_NAME=$(terraform output -raw image_template_resource_name)
                      
                      # Check if template exists before attempting deletion
                      TEMPLATE_EXISTS=$(az resource list \
                        --resource-group "$RESOURCE_GROUP" \
                        --resource-type Microsoft.VirtualMachineImages/imageTemplates \
                        --name "$TEMPLATE_NAME" \
                        --query "[0].id" -o tsv)
                      
                      if [ -n "$TEMPLATE_EXISTS" ]; then
                        echo "Deleting image template '$TEMPLATE_NAME'..."
                        az resource delete \
                          --resource-group "$RESOURCE_GROUP" \
                          --resource-type Microsoft.VirtualMachineImages/imageTemplates \
                          --name "$TEMPLATE_NAME"
                        
                        echo "✓ Image template '$TEMPLATE_NAME' deleted successfully"
                        echo "✓ Staging resources cleaned up"
                        echo "✓ Custom image remains available in the compute gallery"
                      else
                        echo "Image template '$TEMPLATE_NAME' not found. Skipping deletion."
                      fi